//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graph2_projet_integrateur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public string IDAdmission { get; set; }
        public string ChirurgieProgrammee { get; set; }
        public Nullable<System.DateTime> DateAdmission { get; set; }
        public Nullable<System.DateTime> DateChirurgie { get; set; }
        public Nullable<System.DateTime> DateDuConge { get; set; }
        public bool Televiseur { get; set; }
        public bool Telephone { get; set; }
        public string NSS { get; set; }
        public string NumeroLit { get; set; }
        public string IDMedecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
